### ISSUE TITLE
Hide/disable data json under videos

### ISSUE THREAD

**Issue by alicekemp** [okld/streamlit-player#4]
Is there a way to automatically disable or hide the json that shows below each embedded video? I.e. the dictionary that shows the "name" and "data" elements? 

<img width="394" alt="Screen Shot 2022-05-11 at 10 22 59 PM" src="https://user-images.githubusercontent.com/98052656/167985733-091976e2-7f40-4253-bcf5-39fd1dde78cb.png">

**Comment by okld** [comment]
Hello @alicekemp,

Could you share the code you used?
The data shown below the video is returned by `st_player()`. I suspect you're printing it unintentionally like so:

```python
from streamlit_player import st_player

data = st_player("url")
data  # This line will display the dictionary {"name": ..., "data": ...) below the video
```

**Comment by alicekemp** [comment]
> 

Ah, I was defining the function as a variable and calling it - quick fix. Thanks for your help.
