### ISSUE TITLE
How to use events

### ISSUE THREAD

**Issue by aflah02** [okld/streamlit-player#6]
Hi, thanks for the great library.
I want to add some call back functions when the video is played or paused but I can't figure out how to do it. There are events supported but [they just seem to take string inputs](https://github.com/okld/streamlit-player/blob/eae21606ded115b0c32cbfbdaffb73e1044ed016/streamlit_player/__init__.py#L66). Can you please share some code samples to add callback functions to video players?

**Comment by ccl-private** [comment]
Do you make it？
